/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "OrzMC"

include("orzmc-api")

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention").version("0.10.0")
}