name: Publish to Hangar
on:
  push:
    branches:
      - main                # → Snapshot 发布
    tags:
      - '*.*.*'             # → Release 发布（SemVer，无 v 前缀）

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: gradle wrapper validation
        uses: gradle/actions/wrapper-validation@v6

      - name: jdk
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 25

      - name: check (tag only)
        if: github.ref_type == 'tag'
        run: ./gradlew check --stacktrace

      - name: build shadowJar
        run: ./gradlew clean build --stacktrace

      - name: publish to Hangar
        env:
          HANGAR_API_TOKEN: ${{ secrets.HANGAR_API_TOKEN }}
        run: ./gradlew clean publishPluginPublicationToHangar --stacktrace
