name: Create GitHub Release
on:
  push:
    tags:
      - '*.*.*'             # SemVer 格式，无 v 前缀

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: gradle wrapper validation
        uses: gradle/actions/wrapper-validation@v6

      - name: jdk
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21

      - name: build shadowJar
        run: ./gradlew clean build --stacktrace

      - name: create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: build/libs/*.jar
          generate_release_notes: true
